import { Inter } from "next/font/google";
import "../styles/globals.css";
import Link from "next/link";
import db from "./api/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lodi's DEV Blog",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href="/"><img src="/logo.png" alt="Logo"></img></Link>
          <Link href="/list">List</Link>
          <Link href="/cart">Cart</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
